# Generated by Django 5.0.2 on 2024-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
